import { NextRequest, NextResponse } from 'next/server'
import connectDB from '@/lib/mongoose'
import { Transaction } from '@/lib/models'
import jwt from 'jsonwebtoken'
import bcrypt from 'bcryptjs'
import crypto from 'crypto'

const JWT_SECRET = process.env.JWT_SECRET || 'hostel-marketplace-secret'

function getUser(req: NextRequest) {
  try {
    const token = req.cookies.get('token')?.value || req.cookies.get('hm_session')?.value
    if (!token) return null
    return jwt.verify(token, JWT_SECRET) as { userId: string; role: string }
  } catch { return null }
}

export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = getUser(req)
    if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 })
    await connectDB()
    const { id } = await params

    const tx = await Transaction.findById(id)
    if (!tx) return NextResponse.json({ error: 'Transaction not found' }, { status: 404 })
    if (tx.sellerId.toString() !== user.userId) return NextResponse.json({ error: 'Only seller can generate OTP' }, { status: 403 })
    if (!['HANDOVER_PENDING', 'ACCEPTED', 'OTP_GENERATED'].includes(tx.status)) {
      return NextResponse.json({ error: 'Transaction is already completed or closed' }, { status: 400 })
    }

    // Generate 6-digit OTP
    const otpCode = String(Math.floor(100000 + Math.random() * 900000))
    const otpHash = await bcrypt.hash(otpCode, 10)
    const expiry = new Date(Date.now() + 60 * 60 * 1000) // 1 hour validity

    tx.otpCodeHash = otpHash
    tx.plainOtpCode = otpCode
    tx.otpExpiry = expiry
    tx.otpUsed = false
    tx.otpGenerationCount = (tx.otpGenerationCount || 0) + 1
    tx.status = 'OTP_GENERATED'
    await tx.save()

    // Add transaction chat system message
    const { Message } = await import('@/lib/models')
    await new Message({
      transactionId: tx._id,
      senderId: user.userId,
      content: `🔑 [Handover OTP Generated] Code generated by seller. Please meet in person, inspect all item features, and enter the code on the buyer's screen to complete the handover.`,
    }).save()

    console.log(`[OTP GENERATED] Transaction ${id}: ${otpCode}`)

    return NextResponse.json({
      message: 'OTP generated. Share it with the buyer after inspection.',
      otp: otpCode,
      otpCode,
      expiresAt: expiry,
      generationsUsed: tx.otpGenerationCount,
    })
  } catch (err) {
    console.error('[generate-otp]', err)
    return NextResponse.json({ error: 'Server error' }, { status: 500 })
  }
}
